var json= {
  "com.nuance.swype.input":{
    "path":"/custpack/app/unremoveable/withlibs/Swype.apk",
    "versionName":"1.7.13.31408",
    "perso":"all"
  },
  "com.jrdcom.fmradio":{
    "path":"/custpack/app/unremoveable/withoutlibs/FMRadio_v4.0.001.0_signed_platform.apk",
    "versionName":"1.0",
    "perso":"all"
  },
  "com.jrdcom.setupwizard":{
    "path":"/custpack/app/unremoveable/withoutlibs/JrdSetupWizard_common_v4.0.1.001.0_signed.apk",
    "versionName":"v4.0.1.001.0",
    "perso":"all"
  },
  "com.android.soundrecorder":{
    "path":"/custpack/app/unremoveable/withoutlibs/JrdSoundRecorder_common_v1.1.104.0_signed.apk",
    "versionName":"v1.1.104.0",
    "perso":"all"
  },
  "com.jrdcom.launcher":{
    "path":"/custpack/app/unremoveable/withoutlibs/JrdLauncher_common_v2.8.001.0_signed.apk",
    "versionName":"v2.8.001.0",
    "perso":"all"
  },
  "com.jrdcom.alcatelhelp":{
    "path":"/custpack/app/unremoveable/withoutlibs/JrdAlcatelHelp_common_v2.6.014_signed.apk",
    "versionName":"v2.6.014",
    "perso":"all"
  },
  "com.jrdcom.music":{
    "path":"/custpack/app/unremoveable/withlibs/JrdMusic_global_v3.3.010_signed.apk",
    "versionName":"3.3.010",
    "perso":"all"
  },
  "com.jrdcom.wifidirecttransfer":{
    "path":"/custpack/app/unremoveable/withoutlibs/JrdWifiP2PTransfer_1.0.004_signed.apk",
    "versionName":"v1.0.004",
    "perso":"all"
  },
  "com.jrdcom.filemanager":{
    "path":"/custpack/app/unremoveable/withoutlibs/JrdFileManager_common_v1.6.004.0_signed.apk",
    "versionName":"v1.6.004.0",
    "perso":"all"
  },
  "com.jrdcom.weather":{
    "path":"/custpack/app/unremoveable/withoutlibs/JrdWeather_common_v1.8.043_signed.apk",
    "versionName":"v1.8.043",
    "perso":"all"
  },
  "com.jrdcom.ui.notes":{
    "path":"/custpack/app/unremoveable/withoutlibs/JrdNote_common_v4.0.1.001.0_signed.apk",
    "versionName":"v4.0.1.001.0",
    "perso":"all"
  },
  "com.jrdcom.usercardservice":{
    "path":"/custpack/app/unremoveable/withoutlibs/JrdUserCenterService_common_v1.0.216_signed.apk",
    "versionName":"v2.2_409",
    "perso":"all"
  },
  "com.android.calculator2":{
    "path":"/custpack/app/unremoveable/withoutlibs/JrdCalculator_common_v1.5.001.0_signed.apk",
    "versionName":"v1.5.001.0",
    "perso":"all"
  },
  "com.jrdcom.compass":{
    "path":"/custpack/app/unremoveable/withoutlibs/JrdCompass_common_v1.4.006_signed.apk",
    "versionName":"v1.4.006",
    "perso":"all"
  },
  "com.jrdcom.usercard":{
    "path":"/custpack/app/unremoveable/withlibs/JrdUserCenter_common_v1.0.216_signed.apk",
    "versionName":"v1.0.216",
    "perso":"all"
  },
  "com.android.deskclock":{
    "path":"/custpack/app/unremoveable/withoutlibs/JrdTimeTool_common_v1.6.042_signed.apk",
    "versionName":"v1.6.041",
    "perso":"all"
  },
  "com.mobisystems.office":{
    "path":"/custpack/app/unremoveable/withlibs/OfficeSuite_Free_7.5_2077.apk",
    "versionName":"7.5.2077",
    "perso":"all"
  },
  "com.facebook.katana":{
    "path":"/custpack/app/unremoveable/withlibs/facebook.apk",
    "versionName":"17.0.0.23.16",
    "perso":"all"
  },
  "com.twitter.android":{
    "path":"/custpack/app/unremoveable/withlibs/Twitter-5.25.0-release-20140913.apk",
    "versionName":"5.25.0",
    "perso":"all"
  },
  "com.mobitv.client.tmobiletvhd":{
    "path":"/custpack/app/unremoveable/withlibs/TMobile_v6.0.6.2-d334577_2014_06_06_production.apk",
    "versionName":"6.0.6.2-d334577",
    "perso":"tmo"
  },
  "com.tmobile.vvm.application":{
    "path":"/custpack/app/unremoveable/withoutlibs/VVM-5.2.4.2-final-release.apk",
    "versionName":"5.2.4.2",
    "perso":"tmo"
  },
  "com.lookout":{
    "path":"/custpack/app/unremoveable/withlibs/Lookout.apk",
    "versionName":"9.1.3-aeb9077",
    "perso":"tmo"
  },
  "com.tmobile.pr.adapt":{
    "path":"/custpack/app/unremoveable/withoutlibs/AdaptClient.apk",
    "versionName":"1.0.3",
    "perso":"tmo"
  },
  "us.com.dt.iq.appsource.tmobile":{
    "path":"/custpack/app/unremoveable/withoutlibs/AppSource-tmobile-1.2.07-b67-US-PROD.apk",
    "versionName":"1.2.07",
    "perso":"tmo"
  },
  "com.tmobile.pr.mytmobile":{
    "path":"/custpack/app/unremoveable/priv-app/MyAccount.apk",
    "versionName":"3.6.70",
    "perso":"tmo"
  },
  "com.carrieriq.tmobile":{
    "path":"/custpack/app/unremoveable/priv-app/IQtmobile.apk",
    "versionName":"1.28",
    "perso":"tmo"
  },
  "com.customermobile.tmous.preload":{
    "path":"/custpack/app/unremoveable/priv-app/CustomerMobile.apk",
    "versionName":"tmous-0.9.7",
    "perso":"tmo"
  },
  "com.amazon.mShop.android":{
    "path":"/custpack/app/removeable/withlibs/AmazonMobileShop.apk",
    "versionName":"2.10.0",
    "perso":"tmo"
  }
}
