var json= {
  "com.google.android.googlequicksearchbo":{
    "path":"/custpack/app/unremoveable/priv-app/Velvet.apk",
    "versionName":"3.5.16.1262550.arm"
  },
  "com.android.faceloc":{
    "path":"/custpack/app/unremoveable/FaceLock.apk",
    "versionName":"4.4.2-1289630"
  },
  "com.google.android.marvin.talkbac":{
    "path":"/custpack/app/unremoveable/talkback.apk",
    "versionName":"3.5.1"
  },
  "com.google.android.tal":{
    "path":"/custpack/app/unremoveable/Hangouts.apk",
    "versionName":"2.1.311 (1231142-30)"
  },
  "com.google.android.stree":{
    "path":"/custpack/app/unremoveable/Street.apk",
    "versionName":"1.8.1.2"
  },
  "com.google.android.inputmethod.lati":{
    "path":"/custpack/app/unremoveable/LatinImeGoogle.apk",
    "versionName":"3.0.19423.1102675a"
  },
  "com.google.android.video":{
    "path":"/custpack/app/unremoveable/Videos.apk",
    "versionName":"3.2.25"
  },
  "com.google.android.GoogleCamer":{
    "path":"/custpack/app/unremoveable/GoogleCamera.apk",
    "versionName":"2.2.024 (1195242-30)"
  },
  "com.google.android.syncadapters.calenda":{
    "path":"/custpack/app/unremoveable/GoogleCalendarSyncAdapter.apk",
    "versionName":"4.4.4-1230475"
  },
  "com.google.android.apps.cloudprin":{
    "path":"/custpack/app/unremoveable/CloudPrint.apk",
    "versionName":"0.9.10"
  },
  "com.google.android.gallery3":{
    "path":"/custpack/app/unremoveable/GalleryGoogle.apk",
    "versionName":"1.1.40304"
  },
  "com.google.android.apps.book":{
    "path":"/custpack/app/unremoveable/Books.apk",
    "versionName":"3.1.49"
  },
  "com.android.providers.partnerbookmark":{
    "path":"/custpack/app/unremoveable/PartnerBookmarksProvider.apk",
    "versionName":"4.4.2-1289630"
  },
  "com.google.android.apps.genie.geniewidge":{
    "path":"/custpack/app/unremoveable/GenieWidget.apk",
    "versionName":"1.3.11"
  },
  "com.google.android.syncadapters.contact":{
    "path":"/custpack/app/unremoveable/GoogleContactsSyncAdapter.apk",
    "versionName":"4.4.2-1289630"
  },
  "com.google.android.youtub":{
    "path":"/custpack/app/unremoveable/YouTube.apk",
    "versionName":"5.7.41"
  },
  "com.google.android.apps.doc":{
    "path":"/custpack/app/unremoveable/Drive.apk",
    "versionName":"2.0.222.39"
  },
  "com.google.android.apps.magazine":{
    "path":"/custpack/app/unremoveable/Magazines.apk",
    "versionName":"3.2.1"
  },
  "com.google.android.apps.uploade":{
    "path":"/custpack/app/unremoveable/MediaUploader.apk",
    "versionName":"1.3.242047"
  },
  "com.google.android.tt":{
    "path":"/custpack/app/unremoveable/GoogleTTS.apk",
    "versionName":"3.1.3.1162895"
  },
  "com.google.android.play.game":{
    "path":"/custpack/app/unremoveable/PlayGames_alldpi.apk",
    "versionName":"1.6.07 (1129543-30)"
  },
  "com.google.android.apps.plu":{
    "path":"/custpack/app/unremoveable/PlusOne.apk",
    "versionName":"4.4.3.69327528"
  },
  "com.google.android.syncadapters.bookmark":{
    "path":"/custpack/app/unremoveable/ChromeBookmarksSyncAdapter.apk",
    "versionName":"4.4-927798"
  },
  "com.google.android.musi":{
    "path":"/custpack/app/unremoveable/Music2.apk",
    "versionName":"5.6.1609P.1258283"
  },
  "com.android.browser.provide":{
    "path":"/custpack/app/unremoveable/BrowserProviderProxy.apk",
    "versionName":"4.4.2-1289630"
  },
  "com.google.android.deskcloc":{
    "path":"/custpack/app/unremoveable/DeskClockGoogle.apk",
    "versionName":"3.0.0"
  },
  "com.android.chrom":{
    "path":"/custpack/app/unremoveable/Chrome.apk",
    "versionName":"35.0.1916.141"
  },
  "com.google.android.g":{
    "path":"/custpack/app/unremoveable/Gmail2.apk",
    "versionName":"4.8 (1167183)"
  },
  "com.google.android.apps.map":{
    "path":"/custpack/app/unremoveable/Maps_alldpi.apk",
    "versionName":"8.1.1"
  },
  "com.google.android.calenda":{
    "path":"/custpack/app/unremoveable/CalendarGoogle.apk",
    "versionName":"201404014"
  }
}