#!/usr/bin/python
# -*- coding: utf8 -*-
#Get Apk zipalign list 

__author__ = 'Tan Ying<ying.tan@tcl.com>' 

import os
import sys
import re
import getopt
import commands
import shutil
from utils import *

def main():
    # ./zipalign -c -v 4 path

if __name__ == '__main__':
    main()